### ISSUE TITLE
Error in a simple loop

### ISSUE THREAD

**Issue by martindevans** [dwilliamson/dcpu16.js#1]
I have written this code:

http://dwilliamson.github.com/#set%20x%2C%201%0Aset%20Z%2C%200x8000%20%3BScreen%20buffer%0A%0A%3Aloop%0A%09jsr%20writevalue%0A%09%09%0A%09ADD%20x%2C%201%0A%20%20%20%20ifg%20x%2C%2020%09%09%3BLoop%20to%2020%0A%20%20%20%20%20%20%20%20set%20PC%2C%20end%0A%0A%20%20%20%20set%20PC%2C%20loop%0A%0A%3Aend%0A%09set%20PC%2C%20end%0A%0A%3Awritevalue%0A%09set%20I%2C%20X%0A%20%20%20%20ifg%20I%2C%209%0A%20%20%20%20%20%20%20%20DIV%20I%2C%2010%0A%0A%20%20%20%20jsr%20writedigit%0A%0A%20%20%20%20ifg%2010%2C%20X%0A%09%09add%20Z%2C%201%0A%09ifg%2010%2C%20X%0A%20%20%20%20%20%20%20%20SET%20PC%2C%20POP%0A%0A%20%20%20%20set%20I%2C%20X%0A%20%20%20%20mod%20I%2C%2010%0A%0A%20%20%20%20jsr%20writedigit%0A%09%0A%09add%20Z%2C%201%0A%20%20%20%20set%20PC%2C%20POP%0A%09%0A%3Awritedigit%0A%20%20%20%20add%20I%2C%2048%0A%20%20%20%20add%20Z%2C%201%0A%20%20%20%20set%20%5BZ%5D%2C%20I%0A%20%20%20%20set%20PC%2C%20POP

Which should simply loop from 1 to 20 and print the values. Testing this code in this other emulator, http://denull.ru/dcpu/dcpu.htm generates the correct result, but this emulator only prints 1,2,3,4,5,6,7,8,9,10

**Comment by dwilliamson** [comment]
Thanks. Latest code fixes this.
