### ISSUE TITLE
CodeMirror Highlighting

### ISSUE THREAD

**Issue by mappum** [dwilliamson/dcpu16.js#11]
I saw you have a CodeMirror mode for DCPU. I run [0x10code](http://0x10co.de), and I also use CodeMirror. Do you mind if I use your CodeMirror mode for my site?

Just to let you know, you are free to borrow any code you want from my javascript assembler/emulator, as well. I feel like it doesn't make sense for the same work to be done twice.

**Comment by dwilliamson** [comment]
Sure, go for it!

**Comment by mappum** [comment]
Thanks!
