### ISSUE TITLE
change color of message dat .

### ISSUE THREAD

**Issue by catafest** [dwilliamson/dcpu16.js#18]
Try to use LIVE EDIT ENVIRONMENT FOR MOJANG'S DCPU-16 MACHINE 
- change color - not workin , why ?

:data
    dat 0x2e1,"           \o/",0

:start
    set i, 0 ; character index
    set b, 0xf100

:nextchar
    ; Get data from string data, or jump to end
    set a, [data+i]
    ifg a, 0x100
        set PC, end

```
; Get video memory offset
set j, 0x8000
add j, i ; Move cursor to correct column

; Calculate offset to move text
mul y, 32 ; Display is 32 chars wide

; Add line offset value to video-mem offset
add j, y

div y, 32 ; Undo mult, so incrementing line num works

; Set video memory
set [j], a

; Increment character counter
add i, 1
add j, 1
; Loop, until all data is iterated over
set PC, nextchar
```

:end
    ; Clear screen
    JSR sleep
    JSR clearscreen

```
; Increment line
add y, 1

; Wrap line value
ifg y, 11 ; 12 lines
    set y, 0
set PC, start
```

:setcolor
    set b,a
    add b,0xff
    shl b,8
    ifg a , 0x1ff
        add b,0x80
    add i,1
    set PC,nextchar

:clearscreen
    set c, 0
:clearscreenloop
    set z, 32
    mul z, 12
    set [0x8000+c], 0
    add c, 1
    ifg c, z
        set PC, POP
    set PC, clearscreenloop

:sleep
    set x, 0
    set b, 0
:sleeploop
    add b, 1
    ifg b, 0x111
        add x, 1
    ifg b, 0x111
        set b, 0
    ifg x, 10
        set PC, POP
    set PC, sleeploop

**Comment by dwilliamson** [comment]
Is this code copy and pasted from somewhere? It has many errors.

**Comment by dwilliamson** [comment]
Some quick ones:
- First `dat` statement is terminated with 0 which stops it even running. In this emulator all strings are null-terminated so there's no need for this.
- `setcolor` uses `add` not `and`
- Result calculated by `setcolor` is not combined with the character written to video memory.

**Comment by dwilliamson** [comment]
Anyway...

```
:data
    dat 0x2e1,"           \o/"

:start
    set i, 0 ; character index
    set b, 0xf100

:nextchar
    ; Get data from string data, or jump to end
    set a, [data+i]
    ife a, 0
        set PC, end
    ifg a, 0xff
        set PC, setcolor
    bor a, b

    ; Get video memory offset
    set j, 0x8000
    add j, i ; Move cursor to correct column

    ; Calculate offset to move text
    mul y, 32 ; Display is 32 chars wide

    ; Add line offset value to video-mem offset
    add j, y

    div y, 32 ; Undo mult, so incrementing line num works

    ; Set video memory
    set [j], a

    ; Increment character counter
    add i, 1
    add j, 1
    ; Loop, until all data is iterated over
    set PC, nextchar

:end
    ; Clear screen
    JSR sleep
    JSR clearscreen

    ; Increment line
    add y, 1

    ; Wrap line value
    ifg y, 11 ; 12 lines
        set y, 0
    set PC, start

:setcolor
    set b,a
    and b,0xff
    shl b,8
    ifg a , 0x1ff
        add b,0x80
    add i,1
    set PC,nextchar

:clearscreen
    set c, 0
:clearscreenloop
    set z, 32
    mul z, 12
    set [0x8000+c], 0
    add c, 1
    ifg c, z
        set PC, POP
    set PC, clearscreenloop

:sleep
    set x, 0
    set b, 0
:sleeploop
    add b, 1
    ifg b, 0x111
        add x, 1
    ifg b, 0x111
        set b, 0
    ifg x, 10
        set PC, POP
    set PC, sleeploop

```
